feat: Make KRE Jetstream compatible
konstellation-io/kre pull request #634
Opened 2022-07-12 09:36 UTC by alexrodfe

## Why
As our Runners are now Jetstream compatible, we need KRE to be Jetstream compatible as well .

## What
- K8s manager now sets new environment variables regarding stream naming and new node setup.
- K8s manager will delete workflow's streams on version deletion to free up memory.
- There has been also some refactor and renaming

2022-07-13 07:44 UTC, alejandrogr commented on engine/k8s-manager/kubernetes/version/nats.go
> +package version
Yes, I'm with @JYisus we should separate all the NATs code to a separate package

2022-07-13 07:45 UTC, alejandrogr requested changes
This is a major release, we should rise the major version in the github workflow.

2022-07-14 10:51 UTC, alexrodfe commented on engine/k8s-manager/kubernetes/version/nats.go
> +package version
Done :+1:

2022-07-14 10:52 UTC, alexrodfe commented on helm/kre/templates/engine/nats-streaming/statefulset.yaml
> +            storage: {{ .Values.nats_streaming.storage.size }}
Done!

2022-07-14 12:17 UTC, JYisus approved these changes

2022-07-15 07:49 UTC, alejandrogr approved these changes
LGTM! Welcome Jetstream! :D

2022-07-18 08:57 UTC, merged