feat(admin-api): Update echo and generate Go metrics
konstellation-io/kre pull request #677
Opened 2022-10-21 12:04 UTC by aacecandev

2022-11-10 10:04 UTC, JYisus requested changes

2022-11-10 10:04 UTC, JYisus commented on engine/admin-api/delivery/http/middleware/prometheus.nogo
> +// package middleware
@aacecandev @blopezpi Remember to delete this file!

2022-11-10 10:04 UTC, JYisus commented on engine/admin-api/delivery/http/server.go
> +	// graphQLMetricsMiddleware := kremiddleware.NewGraphQlMetricsMiddleware(logger)
@aacecandev @blopezpi Delete unused comments in this file

2023-03-16 10:58 UTC, dfinteligenz commented
@aacecandev @blopezpi I'm seeing that the latest update for this branch is Oct 21, 2022, is this PR still valid?

2023-08-08 06:02 UTC, closed without merging